
name: treinamento
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tupy_framework:
    git:
      url: git@ssh.dev.azure.com:v3/tupysa/MOB_TUPY_FRAMEWORK/MOB_TUPY_FRAMEWORK
      ref: main
  cupertino_icons: ^1.0.2
  badges: 3.1.1
  carousel_slider: ^4.2.0
  flutter_pdfview: ^1.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: 2.9.0
  build_runner: 2.4.5
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/pee.png"  

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
 
